### ISSUE TITLE
Missing usage example for Docker

### ISSUE THREAD

**Issue by Wirone** [mcustiel/phiremock-docker#1]
We would like to use Phiremock in our project but there isn't any documentation about how to use Docker image in project's `docker-compose.yml` and how to define scenarios for Phiremock image.

Any suggestions appreciated :-)

**Comment by wazum** [comment]
Just add the container
```  
phiremock:
    container_name: project_phiremock
    build:
      context: docker/build/phiremock
      dockerfile: Dockerfile
    expose:
      - "8086"
    networks:
      - p2n
    volumes:
      - ./app/phiremock/expectations/:/app/
```

with this Dockerfile

```
FROM composer

RUN composer global require mcustiel/phiremock

ENV COMPOSER_HOME /tmp
ENV PATH /tmp/vendor/bin:$PATH
ENV COMPOSER_ALLOW_SUPERUSER 1

ENTRYPOINT ["phiremock", "-d", "-e", "/app"]
```

and put your expectations into the directory mounted above
